import React, { useState } from 'react';
import { Search, Filter, Play, CheckCircle2, AlertOctagon, StopCircle, RefreshCw, Eye, ShieldAlert, Sparkles, ArrowUpRight } from 'lucide-react';
import { Transaction } from '../types';

interface RecoveryQueueProps {
  queue: Transaction[];
  loading: boolean;
  onRefresh: () => void;
  onSelectTransaction: (id: string) => void;
  onApprove: (id: string) => void;
  onExecute: (id: string) => void;
  onEscalate: (id: string) => void;
  onStop: (id: string) => void;
}

export const RecoveryQueue: React.FC<RecoveryQueueProps> = ({
  queue,
  loading,
  onRefresh,
  onSelectTransaction,
  onApprove,
  onExecute,
  onEscalate,
  onStop
}) => {
  const [search, setSearch] = useState('');
  const [statusFilter, setStatusFilter] = useState('');
  const [reasonFilter, setReasonFilter] = useState('');
  const [processingId, setProcessingId] = useState<string | null>(null);

  const filteredQueue = queue.filter((item) => {
    const matchesSearch =
      item.customer_name.toLowerCase().includes(search.toLowerCase()) ||
      item.id.toLowerCase().includes(search.toLowerCase());
    const matchesStatus = !statusFilter || item.status === statusFilter;
    const matchesReason = !reasonFilter || item.failure_reason === reasonFilter;
    return matchesSearch && matchesStatus && matchesReason;
  });

  const handleAction = async (actionFn: (id: string) => void, id: string) => {
    setProcessingId(id);
    await actionFn(id);
    setProcessingId(null);
  };

  return (
    <div className="p-8 space-y-6">
      {/* Header Info */}
      <div className="flex items-center justify-between">
        <div>
          <h3 className="text-xl font-extrabold text-[#3D2E24] tracking-tight flex items-center gap-2">
            AI Recovery Queue
            <span className="text-xs px-3 py-1 rounded-full font-bold bg-[#047857]/15 text-[#047857] border border-[#047857]/30">
              {filteredQueue.length} Active Candidates
            </span>
          </h3>
          <p className="text-xs text-[#7C6656]">
            Real-time failed payment interventions generated by scikit-learn ML model with guardrails.
          </p>
        </div>
        <button
          onClick={onRefresh}
          className="p-2.5 rounded-xl bg-[#EFE8DC] border border-[#D8CBB5] text-[#5C483A] hover:text-[#3D2E24] hover:bg-[#E8DFC8] text-xs font-semibold flex items-center gap-2"
        >
          <RefreshCw className={`w-3.5 h-3.5 ${loading ? 'animate-spin text-[#8C5D3B]' : ''}`} />
          Refresh Queue
        </button>
      </div>

      {/* Search & Filter Bar */}
      <div className="p-4 rounded-2xl bg-[#F0E8DD] border border-[#D8CBB5] flex items-center gap-4 shadow-xs">
        <div className="relative flex-1">
          <Search className="w-4 h-4 text-[#7C6656] absolute left-3.5 top-3" />
          <input
            type="text"
            placeholder="Search by customer name or transaction ID..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="w-full bg-[#F9F6F0] border border-[#D8CBB5] rounded-xl pl-10 pr-4 py-2 text-xs text-[#3D2E24] placeholder-[#A08C7D] focus:outline-none focus:border-[#8C5D3B]/50"
          />
        </div>

        <div className="flex items-center gap-3">
          <select
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
            className="bg-[#F9F6F0] border border-[#D8CBB5] rounded-xl px-3 py-2 text-xs text-[#3D2E24] focus:outline-none focus:border-[#8C5D3B]/50 font-medium"
          >
            <option value="">All Statuses</option>
            <option value="FAILED">FAILED (Pending Action)</option>
            <option value="REQUIRES_APPROVAL">REQUIRES_APPROVAL (&gt; ₹10k)</option>
            <option value="STOPPED">STOPPED</option>
          </select>

          <select
            value={reasonFilter}
            onChange={(e) => setReasonFilter(e.target.value)}
            className="bg-[#F9F6F0] border border-[#D8CBB5] rounded-xl px-3 py-2 text-xs text-[#3D2E24] focus:outline-none focus:border-[#8C5D3B]/50 font-medium"
          >
            <option value="">All Failure Reasons</option>
            <option value="Insufficient Funds">Insufficient Funds</option>
            <option value="Auth Failed">Auth Failed</option>
            <option value="Card Expired">Card Expired</option>
            <option value="Bank Timeout">Bank Timeout</option>
            <option value="Network Error">Network Error</option>
          </select>
        </div>
      </div>

      {/* Queue Table */}
      <div className="rounded-2xl bg-[#F0E8DD] border border-[#D8CBB5] overflow-hidden shadow-xs">
        <table className="w-full text-left border-collapse">
          <thead>
            <tr className="border-b border-[#D8CBB5] bg-[#E8DFC8] text-[#5C483A] text-[11px] font-bold uppercase tracking-wider">
              <th className="py-4 px-6">Customer / Txn ID</th>
              <th className="py-4 px-4">Amount</th>
              <th className="py-4 px-4">Failure Reason</th>
              <th className="py-4 px-4">Recovery Prob</th>
              <th className="py-4 px-4">Expected Rec</th>
              <th className="py-4 px-4">Recommended Action</th>
              <th className="py-4 px-3 text-center">Retries</th>
              <th className="py-4 px-4">Status</th>
              <th className="py-4 px-6 text-right">Intervention Control</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-[#D8CBB5] text-xs">
            {loading ? (
              <tr>
                <td colSpan={9} className="py-12 text-center text-[#7C6656]">
                  <RefreshCw className="w-6 h-6 animate-spin mx-auto mb-2 text-[#8C5D3B]" />
                  Loading recovery queue...
                </td>
              </tr>
            ) : filteredQueue.length === 0 ? (
              <tr>
                <td colSpan={9} className="py-12 text-center text-[#7C6656]">
                  No matching active recovery items found.
                </td>
              </tr>
            ) : (
              filteredQueue.map((item) => (
                <tr key={item.id} className="hover:bg-[#E8DFC8]/60 transition-colors group">
                  <td className="py-4 px-6 font-medium text-[#3D2E24]">
                    <button
                      onClick={() => onSelectTransaction(item.id)}
                      className="font-bold hover:text-[#8C5D3B] transition-colors text-left block"
                    >
                      {item.customer_name}
                    </button>
                    <span className="text-[11px] text-[#7C6656] font-mono block">{item.id}</span>
                  </td>

                  <td className="py-4 px-4 font-extrabold text-[#3D2E24]">
                    ₹{item.amount?.toLocaleString('en-IN')}
                  </td>

                  <td className="py-4 px-4">
                    <span className="px-2.5 py-1 rounded-lg bg-[#EFE8DC] text-[#5C483A] font-semibold border border-[#D8CBB5] text-[11px]">
                      {item.failure_reason}
                    </span>
                  </td>

                  <td className="py-4 px-4">
                    <div className="flex items-center gap-2">
                      <div className="w-12 bg-[#E8DFC8] h-2 rounded-full overflow-hidden">
                        <div
                          className="h-full bg-[#047857] rounded-full"
                          style={{ width: `${item.recovery_probability}%` }}
                        />
                      </div>
                      <span className="font-extrabold text-[#047857]">{item.recovery_probability}%</span>
                    </div>
                  </td>

                  <td className="py-4 px-4 font-bold text-[#0284C7]">
                    ₹{item.expected_recovery?.toLocaleString('en-IN')}
                  </td>

                  <td className="py-4 px-4 font-semibold text-[#3D2E24]">
                    <div className="flex items-center gap-1.5">
                      <Sparkles className="w-3.5 h-3.5 text-[#8C5D3B]" />
                      {item.recommended_action}
                    </div>
                  </td>

                  <td className="py-4 px-3 text-center font-bold text-[#5C483A]">
                    {item.retry_count}/3
                  </td>

                  <td className="py-4 px-4">
                    {item.requires_human_approval ? (
                      <span className="px-2.5 py-1 rounded-full text-[11px] font-bold bg-[#D97706]/15 text-[#B45309] border border-[#D97706]/30 flex items-center gap-1 w-fit animate-pulse">
                        <ShieldAlert className="w-3 h-3" /> APPROVAL REQD
                      </span>
                    ) : item.status === 'STOPPED' ? (
                      <span className="px-2.5 py-1 rounded-full text-[11px] font-bold bg-[#EFE8DC] text-[#7C6656] border border-[#D8CBB5]">
                        STOPPED
                      </span>
                    ) : (
                      <span className="px-2.5 py-1 rounded-full text-[11px] font-bold bg-[#C2410C]/15 text-[#C2410C] border border-[#C2410C]/30">
                        {item.status}
                      </span>
                    )}
                  </td>

                  <td className="py-4 px-6 text-right">
                    <div className="flex items-center justify-end gap-2">
                      <button
                        onClick={() => onSelectTransaction(item.id)}
                        className="p-1.5 rounded-lg bg-[#EFE8DC] text-[#5C483A] hover:text-[#3D2E24] border border-[#D8CBB5]"
                        title="View Details"
                      >
                        <Eye className="w-4 h-4" />
                      </button>

                      {item.requires_human_approval ? (
                        <button
                          onClick={() => handleAction(onApprove, item.id)}
                          disabled={processingId === item.id}
                          className="px-3 py-1.5 rounded-lg bg-[#D97706]/20 text-[#B45309] border border-[#D97706]/40 hover:bg-[#D97706]/30 font-bold text-xs flex items-center gap-1"
                        >
                          <CheckCircle2 className="w-3.5 h-3.5" /> Approve
                        </button>
                      ) : (
                        <button
                          onClick={() => handleAction(onExecute, item.id)}
                          disabled={processingId === item.id}
                          className="px-3 py-1.5 rounded-lg bg-gradient-to-r from-[#8C5D3B] to-[#B4886B] text-white font-bold text-xs shadow-xs hover:from-[#734A2C] hover:to-[#A3775B] flex items-center gap-1 cursor-pointer"
                        >
                          <Play className="w-3.5 h-3.5 fill-white" /> Execute
                        </button>
                      )}

                      <button
                        onClick={() => handleAction(onEscalate, item.id)}
                        disabled={processingId === item.id}
                        className="p-1.5 rounded-lg bg-purple-500/10 text-purple-700 hover:bg-purple-500/20 border border-purple-500/30"
                        title="Escalate Customer"
                      >
                        <AlertOctagon className="w-4 h-4" />
                      </button>

                      <button
                        onClick={() => handleAction(onStop, item.id)}
                        disabled={processingId === item.id}
                        className="p-1.5 rounded-lg bg-[#EFE8DC] text-[#7C6656] hover:text-[#C2410C] border border-[#D8CBB5]"
                        title="Stop Retries"
                      >
                        <StopCircle className="w-4 h-4" />
                      </button>
                    </div>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
};
